#插件作者: 2457043027
#接各种1.8+spigot插件定制
#使用插件请遵守如下规则
#1. 允许转载，但是请标注原作者
#2. 允许修改，魔改。且允许魔改后出售
#3. 允许声明插件是你专用的
#4. 禁止将公开版本用在商业用途
#5. 禁止转载时标注你自己为原作者
#6. 禁止宣称此插件为你自己所写
name: ItemPrefix
main: org.sct.itemprefix.ItemPrefix
version: 1.0
author: [SCT_Alchemy]